# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: turn-based-dev

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.20.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

requests:
  memory: "64Mi"
  cpu: "128m"
limits:
  memory: "128Mi"
  cpu: "256m"