namespace: turn-based-prod

labels:
  env: prod
  tier: backend

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.20.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

requests:
  memory: "128Mi"
  cpu: "256m"
limits:
  memory: "256Mi"
  cpu: "512m"

service:
  type: ClusterIP
  port: 80

ingress:
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
  - host: api-ingress-prod.com
    paths:
    - pathType: Prefix
      path: "/"
      backend:
        service:
          name: api-service-prod
          port:
            number: 80
  tlsEnabled: false              
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local